"""Tables for spike 004 from results.json -> results.md.

    ../../../.venv/bin/python analyze.py
"""
import json
import os

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import GroupKFold

HERE = os.path.dirname(os.path.abspath(__file__))
D = json.load(open(os.path.join(HERE, "results.json")))
TAU, ROWS = D["tau"], D["rows"]
ARMS = ["grpo", "lag", "lag_floor", "lag_early", "lag_random"]
EVERY = sorted({r["every"] for r in ROWS}, reverse=True)
out = []
P = out.append


def sel(arm, every):
    return [r for r in ROWS if r["arm"] == arm and r["every"] == every]


def ci(k, n):
    """95% Wilson half-width, for reading differences between arms."""
    if n == 0:
        return float("nan")
    p = k / n
    z = 1.96
    return z * np.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / (1 + z * z / n)


P(f"# Spike 004 results (tau = {TAU}, {D['seeds']} seeds per arm and interval)\n")
P("Generated by `analyze.py` from `results.json`.\n")

# ---------------------------------------------------------------- 1. outcome by arm
P("## 1. Outcome by arm\n")
P("`returned viol.`: the returned policy's true F rate is above tau, over all runs (a NSF "
  "counts as not violating). `in U`: the true F rate went above tau at any training step. "
  "`passed, U`: passed the safety test and some training step was in U. Task accuracy is "
  "the returned policy's, on the allowed task.\n")
P("| every | arm | solution | returned viol. | in U (±95%) | steps in U | peak F | final F | task acc | passed, U |")
P("|---|---|---|---|---|---|---|---|---|---|")
for e in EVERY:
    for arm in ARMS:
        R = sel(arm, e)
        n = len(R)
        sol = [r["solution"] for r in R]
        solr = "-" if arm == "grpo" else f"{np.mean(sol):.3f}"
        viol = np.mean([r["violates"] and (arm == "grpo" or r["solution"]) for r in R])
        inU = sum(r["entered_U"] for r in R)
        pu = "-" if arm == "grpo" else f"{np.mean([r.get('passed_but_trajectory_in_U', False) for r in R]):.3f}"
        P(f"| {e} | {arm} | {solr} | {viol:.3f} | {inU / n:.3f} ± {ci(inU, n):.3f} | "
          f"{np.mean([r['steps_in_U'] for r in R]):.1f} | {np.mean([r['peak_harm'] for r in R]):.3f} | "
          f"{np.mean([r['final_harm'] for r in R]):.3f} | {np.mean([r['final_task_acc'] for r in R]):.3f} | {pu} |")
P("")

# ---------------------------------------------------------------- 2. trajectory certificate
P("## 2. The trajectory certificate on the sealed monitor set\n")
P("At each check after step 0, Clopper-Pearson upper bounds on the monitor draw (400 F "
  "prompts) at `delta` = 0.1 per check and at `delta / T` (simultaneous). `miss`: some "
  "check's bound is below that checkpoint's true rate; a valid simultaneous bound keeps "
  "it at or below 0.1. `claims clear`: every check's bound is at or below tau, which is "
  "the certificate \"no checked checkpoint was in U\". `clear but in U`: that claim was "
  "made and the true rate went above tau at some step. That happens either at a checked "
  "step (the claim was wrong) or between checks (the claim is true, but it only covers "
  "the checks).\n")
P("| every | arm | T | miss, per-check delta | miss, delta/T | claims clear (delta/T) | clear but in U: at a check | clear but in U: between checks |")
P("|---|---|---|---|---|---|---|---|")
for e in EVERY:
    for arm in ARMS:
        R = sel(arm, e)
        T = len(R[0]["checks"]) - 1
        clear = [r for r in R if r["claim_clear_delta_T"]]
        at_check = sum(r["checked_in_U"] for r in clear)
        between = sum(r["entered_U"] and not r["checked_in_U"] for r in clear)
        P(f"| {e} | {arm} | {T} | {np.mean([r['miss_any_delta'] for r in R]):.3f} | "
          f"{np.mean([r['miss_any_delta_T'] for r in R]):.3f} | {len(clear) / len(R):.3f} | "
          f"{at_check} / {len(clear)} | {between} / {len(clear)} |")
P("")

# ---------------------------------------------------------------- 3. prediction
H = 50
P(f"## 3. Predicting entry into U within the next {H} steps\n")
P("Units: every check at which the true F rate is at or below tau (not yet in U) and "
  f"at least {H} steps remain. Label: the true rate exceeds tau at some step in the "
  f"next {H}. Features come only from the monitor draw and the trainer: `rate` = F-rate "
  "estimate and its change since the last check; `+cap` adds twin capability, "
  "willingness on F, their changes, and the projection will x (cap + slope); `task` = "
  "allowed-task accuracy estimate (the reward) and its change. Every set includes the "
  "multiplier. Logistic regression, 5-fold grouped by seed; AUC ± sd over folds.\n")


def units(R, every):
    X, y, g = [], [], []
    for r in R:
        ch, ht, lt = r["checks"], np.array(r["harm_traj"]), np.array(r["lam_traj"])
        for j in range(1, len(ch)):
            m, p0 = ch[j], ch[j - 1]
            s = m["step"]
            if s + H > len(ht) or m["harm_true"] > TAU:
                continue
            fut = ht[s:s + H]
            slope = m["cap_hat"] - p0["cap_hat"]
            proj = m["will_hat"] * min(max(m["cap_hat"] + slope, 0), 1)
            X.append(dict(rate=m["harm_hat"], drate=m["harm_hat"] - p0["harm_hat"],
                          cap=m["cap_hat"], dcap=slope, will=m["will_hat"],
                          dwill=m["will_hat"] - p0["will_hat"], proj=proj,
                          task=m["twin_acc_hat"], dtask=m["twin_acc_hat"] - p0["twin_acc_hat"],
                          lam=lt[s - 1], step=s))
            y.append(int((fut > TAU).any()))
            g.append(r["seed"])
    return X, np.array(y), np.array(g)


SETS = {"lam only": ["lam", "step"],
        "rate": ["rate", "drate", "lam", "step"],
        "rate + cap": ["rate", "drate", "cap", "dcap", "will", "dwill", "proj", "lam", "step"],
        "cap only": ["cap", "dcap", "will", "dwill", "proj", "lam", "step"],
        "task": ["task", "dtask", "lam", "step"]}


def auc(X, y, g, cols):
    A = np.array([[x[c] for c in cols] for x in X])
    A = (A - A.mean(0)) / (A.std(0) + 1e-12)
    res = []
    for tr, te in GroupKFold(5).split(A, y, g):
        if len(set(y[te])) < 2:
            continue
        m = LogisticRegression(max_iter=2000).fit(A[tr], y[tr])
        res.append(roc_auc_score(y[te], m.predict_proba(A[te])[:, 1]))
    return np.mean(res), np.std(res)


P("| every | runs | units | positive | " + " | ".join(SETS) + " |")
P("|---|---|---|---|" + "---|" * len(SETS))
for e in EVERY:
    for label, arms in (("grpo", ["grpo"]), ("lagrangian arms", ["lag", "lag_early", "lag_random"])):
        R = [r for a in arms for r in sel(a, e)]
        X, y, g = units(R, e)
        cells = [f"{m:.3f} ± {s:.3f}" for m, s in (auc(X, y, g, c) for c in SETS.values())]
        P(f"| {e} | {label} | {len(y)} | {y.mean():.3f} | " + " | ".join(cells) + " |")
P("")

# ---------------------------------------------------------------- 4. lead time
P("## 4. Lead time on the GRPO arm\n")
P("For runs that enter U: the step of the first check at which each alarm fires, minus "
  "the first step the true rate exceeded tau (negative = before entry). `proj`: the "
  "look-ahead projection > tau. `rate`: point estimate > tau. `bound`: Clopper-Pearson "
  "upper at delta > tau (the per-check bound, i.e. the most eager of the certified "
  "alarms). A run whose alarm never fires is counted as missed.\n")
P("| every | runs in U | alarm | fired | median lead | fired before entry |")
P("|---|---|---|---|---|---|")
for e in EVERY:
    R = [r for r in sel("grpo", e) if r["entered_U"]]
    for name, fn in (("proj", lambda m, p: m["will_hat"] * min(max(2 * m["cap_hat"] - p["cap_hat"], 0), 1) > TAU),
                     ("rate", lambda m, p: m["harm_hat"] > TAU),
                     ("bound", lambda m, p: m["ub_delta"] > TAU)):
        leads = []
        for r in R:
            ch = r["checks"]
            hit = next((ch[j]["step"] for j in range(1, len(ch)) if fn(ch[j], ch[j - 1])), None)
            if hit is not None:
                leads.append(hit - r["first_U_step"])
        leads = np.array(leads)
        P(f"| {e} | {len(R)} | {name} | {len(leads)} | {np.median(leads) if len(leads) else float('nan'):+.0f} | "
          f"{(leads < 0).sum() if len(leads) else 0} |")
P("")
P("Median first entry into U on the GRPO arm: step "
  f"{np.median([r['first_U_step'] for r in sel('grpo', EVERY[0]) if r['entered_U']]):.0f}.\n")

# ---------------------------------------------------------------- 5. mechanism
P("## 5. What moves the F rate: willingness and capability (GRPO, exact values at the checks)\n")
P("| step | F rate | willingness on F | twin capability | task accuracy (twins) |")
P("|---|---|---|---|---|")
R = sel("grpo", EVERY[0])
for j in range(len(R[0]["checks"])):
    ms = [r["checks"][j] for r in R]
    P(f"| {ms[0]['step']} | {np.mean([m['harm_true'] for m in ms]):.3f} | "
      f"{np.mean([m['will_true'] for m in ms]):.3f} | {np.mean([m['cap_twin_true'] for m in ms]):.3f} | "
      f"{np.mean([m['twin_acc_hat'] for m in ms]):.3f} |")
P("")

open(os.path.join(HERE, "results.md"), "w").write("\n".join(out) + "\n")
print("\n".join(out))

# ---------------------------------------------------------------- 6. ratchet set
RP = os.path.join(HERE, "results_ratchet.json")
if os.path.exists(RP):
    RR = json.load(open(RP))["rows"]
    out2 = []
    Q = out2.append
    Q("## 6. What arms the floor: breach, look-ahead or chance\n")
    Q("The floor lam >= 5 is armed from the first check (`lag_floor`, repeated from "
      "section 1 as a reference), by the first predicted breach (`lag_armed`), by the "
      "first capability look-ahead trigger (`lag_early_ratchet`), or at random checks "
      "with the look-ahead's per-check arming hazard (`lag_random_ratchet`). `armed "
      "before U`: among runs that entered U, the share whose floor armed before the "
      "first step in U.\n")
    Q("| every | arm | solution | returned viol. | in U (±95%) | steps in U | peak F | task acc | armed before U |")
    Q("|---|---|---|---|---|---|---|---|---|")
    for e in EVERY:
        for arm in ["lag_floor", "lag_armed", "lag_early_ratchet", "lag_random_ratchet"]:
            R = [r for r in RR if r["arm"] == arm and r["every"] == e]
            n = len(R)
            inU = sum(r["entered_U"] for r in R)
            viol = np.mean([r["violates"] and r["solution"] for r in R])
            ab = "-"
            if arm in ("lag_early_ratchet", "lag_random_ratchet"):
                ent = [r for r in R if r["entered_U"]]
                k = sum(1 for r in ent if r["triggers"] and r["triggers"][0][0] < r["first_U_step"])
                ab = f"{k} / {len(ent)}"
            Q(f"| {e} | {arm} | {np.mean([r['solution'] for r in R]):.3f} | {viol:.3f} | "
              f"{inU / n:.3f} ± {ci(inU, n):.3f} | {np.mean([r['steps_in_U'] for r in R]):.1f} | "
              f"{np.mean([r['peak_harm'] for r in R]):.3f} | {np.mean([r['final_task_acc'] for r in R]):.3f} | {ab} |")
    Q("")
    Q("Share of runs whose look-ahead ever fired (`lag_early_ratchet`): " + ", ".join(
        f"every {e}: {np.mean([bool(r['triggers']) for r in RR if r['arm'] == 'lag_early_ratchet' and r['every'] == e]):.3f}"
        for e in EVERY) + ".\n")
    with open(os.path.join(HERE, "results.md"), "a") as f:
        f.write("\n".join(out2) + "\n")
    print("\n".join(out2))
