"""A LaTeX copy of the certification paper, generated from the clean Markdown copy.

Reads ``reports/paper_certification_clean.md`` (itself generated by ``scripts/paper_clean.py``)
and writes ``reports/latex/paper_certification.tex``: a plain ``article``, no venue style.
Section, table and figure numbers are the Markdown's own (the text cites them by number, so
captions carry the number literally and sections are checked against LaTeX's counters). Inline
code that is a formula is typeset as mathematics; file names and identifiers stay monospace.
The Markdown stays the source: edit the working draft, run ``paper_clean.py``, then this.

    python3 scripts/paper_latex.py            # the .tex only
    python3 scripts/paper_latex.py --build    # and the PDF (latexmk from TinyTeX, in ~/.local/bin)
"""
import os
import re
import subprocess
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
SRC = os.path.join(ROOT, "reports", "paper_certification_clean.md")
OUT_DIR = os.path.join(ROOT, "reports", "latex")
DST = os.path.join(OUT_DIR, "paper_certification.tex")

PREAMBLE = r"""\documentclass[11pt]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\usepackage{graphicx,booktabs,longtable,array,caption,enumitem,fancyvrb,microtype}
\usepackage[hidelinks]{hyperref}
\captionsetup{font=small,justification=raggedright,singlelinecheck=false}
\AtBeginDocument{\setlength{\LTcapwidth}{\linewidth}}
\setlist{itemsep=2pt,topsep=4pt}
\emergencystretch=2em
"""

# ------------------------------------------------------------------ formulas written in ASCII

GREEK = {"theta", "delta", "tau", "lambda", "rho", "pi", "kappa", "eta", "sigma", "mu"}
NAMED = {"ln": r"\ln", "max": r"\max", "min": r"\min", "sum": r"\sum"}
OPER = {"mean", "var", "cov", "clip", "rel", "sd"}
ROMAN = {"se", "Beta"}
CODE = {"b1w", "b1", "ppi_py", "security", "SeldonianLLMPolicy", "GLIDE"}
BARE_ONE = r"n_s|ICC_ref|ICC_cand|rho\^2"                         # formulas the prose writes without backticks
BARE = rf"(?<![\w`/.])({BARE_ONE})(?![\w/.])"
TOKEN = re.compile(r"\s+|\d+(?:[.,]\d+)*|[A-Za-z]+|<=|>=|!=|<-|\.\.\.|\.\.|.", re.S)


def is_code(span):
    return (span in CODE or span.endswith("/") or bool(re.search(r"\.(py|md|json|bib|sh|tex)$", span))
            or bool(re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_./-]+", span)))


def _match(toks, i, open_, close):
    """Index of the bracket closing the one at ``i``."""
    depth = 0
    for j in range(i, len(toks)):
        if toks[j] == open_:
            depth += 1
        elif toks[j] == close:
            depth -= 1
            if depth == 0:
                return j
    raise ValueError(f"unbalanced {open_} in formula: {''.join(toks)}")


def _sub(tok):
    if tok in GREEK:
        return "\\" + tok
    if tok in NAMED:
        return NAMED[tok]
    return tok if len(tok) == 1 or tok.isdigit() else rf"\mathrm{{{tok}}}"


def _next(toks, i):
    """Index of the next token that is not white space (``len(toks)`` if none)."""
    while i < len(toks) and toks[i].isspace():
        i += 1
    return i


def _conv(toks):
    out, words, i = [], [], 0

    def flush():
        if words:
            out.append(r"\text{" + " ".join(words) + "}")
            words.clear()

    while i < len(toks):
        t = toks[i]
        if t.isspace():
            if words and len(t) < 3:
                i += 1
                continue                      # a space between two words of prose, or before a symbol
            flush()
            out.append(r"\qquad " if len(t) >= 3 else " ")
        elif re.fullmatch(r"[A-Za-z]+", t):
            star, subs, j = False, [], i + 1
            if j < len(toks) and toks[j] == "*":
                star, j = True, j + 1
            while j + 1 < len(toks) and toks[j] == "_":
                if toks[j + 1] == "{":
                    k = _match(toks, j + 1, "{", "}")
                    subs.append(_conv(toks[j + 2:k]))
                    j = k + 1
                else:
                    subs.append(toks[j + 1])
                    j += 2
            hat = "hat" in subs
            subs = [s if "\\" in s or " " in s else _sub(s) for s in subs if s != "hat"]
            nxt = toks[_next(toks, j)] if _next(toks, j) < len(toks) else ""
            if t == "sqrt" and nxt == "(":
                a = _next(toks, j)
                k = _match(toks, a, "(", ")")
                flush()
                out.append(r"\sqrt{" + _conv(toks[a + 1:k]).strip() + "}")
                i = k + 1
                continue
            if t in GREEK:
                base = "\\" + t
            elif t in NAMED:
                base = NAMED[t]
            elif t in OPER:
                base = rf"\operatorname{{{t}}}"
            elif t == "E" and (subs or nxt == "["):
                base = r"\mathbb{E}"
            elif t == "P" and nxt == "(":
                base = r"\mathbb{P}"
            elif t == "in":
                base = r"\in"
            elif len(t) == 1:
                base = t
            elif t in ROMAN or t.isupper():
                base = rf"\mathrm{{{t}}}"
            elif not (subs or star or hat):
                words.append(t)                # a word of prose inside the formula
                i = j
                continue
            else:
                base = rf"\mathrm{{{t}}}"
            if words:
                words.append("")               # keep a space between the prose and what follows
                flush()
            if hat:
                base = rf"\hat{{{base}}}"
            out.append(base + ("^{*}" if star else "") + ("_{" + ",".join(subs) + "}" if subs else "") + " ")
            i = j
            continue
        else:
            if words and t not in ",.;:)":
                words.append("")
            flush()
            if t == "^":
                j = i + 1
                if toks[j] in "({":
                    k = _match(toks, j, toks[j], ")" if toks[j] == "(" else "}")
                    out.append("^{" + _conv(toks[j + 1:k]).strip() + "}")
                    i = k + 1
                else:
                    out.append("^{" + toks[j] + "}")
                    i = j + 1
                continue
            if t == "." and _next(toks, i + 1) < len(toks) and toks[_next(toks, i + 1)] == "|":
                out.append(r"\cdot ")
            else:
                out.append({"<=": r"\le ", ">=": r"\ge ", "!=": r"\ne ", "<-": r"\leftarrow ", "~": r"\sim ",
                            "..": r",\dots,", "...": r"\dots ", "*": r"\cdot ", "|": r"\mid ", "{": r"\{",
                            "}": r"\}", "%": r"\%", "&": r"\&", "#": r"\#"}.get(t, t))
        i += 1
    flush()
    return "".join(out)


def math(src):
    """ASCII formula -> LaTeX math (without the dollar signs)."""
    s = re.sub(r"\s+=\s+", " = ", src.strip(), count=1).replace("G ~", "G ~~")
    tex = _conv(TOKEN.findall(s)).replace(r"\sim \sim", r"\approx")
    tex = re.sub(r"\\text\{([^}]*) \}", r"\\text{\1}\\ ", tex)     # prose followed by a symbol
    tex = re.sub(r"(?<=[\w})]) ?\\text\{", r"\\ \\text{", tex)      # a symbol followed by prose
    return re.sub(r" +", " ", tex).strip()


# ------------------------------------------------------------------ prose

def esc(text):
    text = re.sub(r'"([^"]*)"', r"``\1''", text)
    text = text.replace("\\", r"\textbackslash{}")
    for a, b in (("&", r"\&"), ("%", r"\%"), ("#", r"\#"), ("$", r"\$"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}"),
                 ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}")):
        text = text.replace(a, b)
    text = text.replace(r"\textbackslash\{\}", r"\textbackslash{}")
    text = re.sub(r"(?<![\w.,-])(\d[\d.,]*(?:\\%)?)-(\d[\d.,]*(?:\\%)?)(?![\w-]|[.,]\d)", r"\1--\2", text)   # ranges
    text = re.sub(r"(?<![\w.,)\]-])-(\d)", r"$-$\1", text)                                           # negatives
    text = re.sub(r"\*\*(.+?)\*\*", r"\\textbf{\1}", text)
    return re.sub(r"(?<!\*)\*([^*\s][^*]*?)\*(?!\*)", r"\\emph{\1}", text)


def inline(text, heading=False):
    if "**" in text:
        # bold first, so that a bold span holding a code span (**`b1w` at rare rates**) is still one span
        return "".join(rf"\textbf{{{inline(p, heading)}}}" if i % 2 else inline(p, heading)
                       for i, p in enumerate(re.split(r"\*\*(.+?)\*\*", text)) if p)
    parts = re.split(r"(`[^`]*`)", text)
    out = []
    for p in parts:
        if p.startswith("`") and p.endswith("`") and len(p) > 1:
            span = p[1:-1]
            if is_code(span):
                tex = (r"\texttt{" + esc(span).replace("--", "-{}-").replace("/", r"/\allowbreak ").replace(r"\_", r"\_\allowbreak ")
                       + "}")
            else:
                tex = "$" + math(span) + "$"
                if heading:
                    tex = rf"\texorpdfstring{{{tex}}}{{{span.replace('_', '-')}}}"
            out.append(tex)
        else:
            for q in re.split(BARE, p):
                out.append("$" + math(q) + "$" if re.fullmatch(BARE_ONE, q) else esc(q))
    return "".join(out)


def table(rows, caption):
    cells = [[c.strip() for c in r.strip().strip("|").split("|")] for r in rows]
    cells = [r for r in cells if not all(re.fullmatch(r":?-{2,}:?", c) for c in r)]
    head, body = cells[0], cells[1:]
    n = len(head)
    plain = [[re.sub(r"[*`]", "", c) for c in r] for r in cells]
    w = []
    for i in range(n):
        lens = [len(r[i]) for r in plain if i < len(r)]
        w.append(min(max(0.5 * max(lens) + 0.5 * sum(lens) / len(lens), 8.5), 42.0))
    w = [max(x, 0.06 * sum(w)) for x in w]            # no column narrower than a short number
    scale = (1.0 - 0.018 * n) / sum(w)
    spec = "".join(rf">{{\raggedright\arraybackslash}}p{{{x * scale:.3f}\linewidth}}" for x in w)

    def row(r, bold=False):
        cs = [r"\hspace{0pt}" + inline(c) if c else "" for c in r] + [""] * (n - len(r))      # \hspace lets a first word hyphenate
        if bold:
            cs = [rf"\textbf{{{c}}}" if c else "" for c in cs]
        return " & ".join(cs) + r" \\"

    out = [r"\begingroup\footnotesize\setlength{\tabcolsep}{4pt}", rf"\begin{{longtable}}{{@{{}}{spec}@{{}}}}"]
    if caption:
        out.append(rf"\caption*{{\textbf{{Table {caption[0]}.}} {inline(caption[1])}}}\\")
    out += [r"\toprule", row(head, bold=True), r"\midrule", r"\endhead", r"\bottomrule", r"\endlastfoot"]
    out += [row(r) for r in body]
    out += [r"\end{longtable}", r"\endgroup"]
    return "\n".join(out)


def display(buf):
    if any(re.match(r"\d+\. ", ln) for ln in buf):                 # the algorithm listing
        return "\\begin{Verbatim}[fontsize=\\small]\n" + "\n".join(buf) + "\n\\end{Verbatim}"
    lines = [math(ln) for ln in buf if ln.strip()]
    if len(lines) == 1:
        return "\\[\n" + lines[0] + "\n\\]"
    return "\\begin{gather*}\n" + " \\\\\n".join(lines) + "\n\\end{gather*}"


def convert(src):
    lines = src.splitlines()
    out, para, i = [], [], 0
    title, mode, caption, figure, after_display = None, "front", None, None, False
    sec, sub, app = 0, 0, 0

    def flush():
        nonlocal para, caption, figure, after_display
        if not para:
            return
        text = " ".join(para)
        para = []
        cont, after_display = after_display and (text[0].islower() or text[0] == "`"), False
        m = re.fullmatch(r"\*Table ([A\d]+)\. (.*)\*", text)
        if m:
            caption = (m.group(1), m.group(2))
            return
        m = re.fullmatch(r"\*Figure (\d+)\. (.*)\*", text)
        if m and figure:
            out.append("\\begin{figure}[htbp]\n\\centering\n" + rf"\includegraphics[width=\linewidth]{{{figure}}}" + "\n"
                       + rf"\caption*{{\textbf{{Figure {m.group(1)}.}} {inline(m.group(2))}}}" + "\n\\end{figure}")
            figure = None
            return
        if mode == "front":
            return                             # the generator's note under the title
        if cont:
            out[-1] = out[-1] + "\n" + inline(text) + "\n"
        else:
            out.append(inline(text) + "\n")

    while i < len(lines):
        line = lines[i]
        if line.startswith("```"):
            flush()
            j = i + 1
            while not lines[j].startswith("```"):
                j += 1
            # a display joins the paragraph before it; a paragraph may open with a bold run-in, a block (\begin, \section) may not
            if out and not re.match(r"\\(?!textbf|emph|texttt)", out[-1]) and out[-1].endswith("\n"):
                out[-1] = out[-1].rstrip("\n") + "\n" + display(lines[i + 1:j])
            else:
                out.append(display(lines[i + 1:j]))
            after_display = True
            i = j + 1
            continue
        m = re.match(r"^(#{1,3})\s+(.*)$", line)
        if m:
            flush()
            level, text = len(m.group(1)), m.group(2).strip()
            if level == 1:
                title = text
            elif text == "Abstract":
                mode = "abstract"
                out.append(r"\begin{abstract}")
            else:
                if mode == "abstract":
                    out.append(r"\end{abstract}")
                mode = "body"
                if text == "References":
                    out.append(r"\section*{References}" + "\n\\begingroup\\small")
                    mode = "refs"
                elif text.startswith("Appendix "):
                    if not app:
                        out.append("\\endgroup\n\\appendix")
                    app += 1
                    letter, name = re.fullmatch(r"Appendix ([A-Z])\. (.*)", text).groups()
                    assert letter == chr(64 + app), text
                    out.append(rf"\section{{{inline(name, heading=True)}}}")
                elif level == 2:
                    num, name = re.fullmatch(r"(\d+)\. (.*)", text).groups()
                    sec, sub = sec + 1, 0
                    assert int(num) == sec, text
                    out.append(rf"\section{{{inline(name, heading=True)}}}")
                else:
                    num, name = re.fullmatch(r"(\d+\.\d+) (.*)", text).groups()
                    sub += 1
                    assert num == f"{sec}.{sub}", text
                    out.append(rf"\subsection{{{inline(name, heading=True)}}}")
            i += 1
            continue
        if line.lstrip().startswith("|"):
            flush()
            j = i
            while j < len(lines) and lines[j].lstrip().startswith("|"):
                j += 1
            out.append(table(lines[i:j], caption))
            caption = None
            i = j
            continue
        m = re.match(r"^(\s*)([-*]|\d+\.)\s+(.*)$", line)
        if m:
            flush()
            ordered = m.group(2)[0].isdigit()
            items, j = [], i
            while j < len(lines):
                mm = re.match(r"^(\s*)([-*]|\d+\.)\s+(.*)$", lines[j])
                if mm and (mm.group(2)[0].isdigit()) == ordered:
                    items.append(mm.group(3))
                    j += 1
                elif lines[j].startswith("  ") and items and lines[j].strip():
                    items[-1] += " " + lines[j].strip()
                    j += 1
                else:
                    break
            env = "enumerate" if ordered else "itemize"
            out.append(rf"\begin{{{env}}}" + "\n" + "\n".join(r"\item " + inline(x) for x in items) + "\n" + rf"\end{{{env}}}")
            i = j
            continue
        m = re.match(r"^!\[(.*?)\]\((\S+)\)\s*$", line)
        if m:
            flush()
            figure = "../" + re.sub(r"\.png$", ".pdf", m.group(2))
            i += 1
            continue
        if not line.strip():
            flush()
        else:
            para.append(line.strip())
        i += 1
    flush()
    if mode == "refs" and not app:
        out.append("\\endgroup")
    date = re.search(r"\*Draft of (\d{4}-\d{2}-\d{2})", src).group(1)
    head = (PREAMBLE + rf"\title{{{inline(title)}}}" + "\n\\author{}\n"
            + rf"\date{{Draft of {date}, not formatted for any venue}}" + "\n\\begin{document}\n\\maketitle\n")
    return head + "\n\n".join(out) + "\n\\end{document}\n"


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    tex = convert(open(SRC).read())
    open(DST, "w").write(tex)
    print(f"{DST}: {len(tex.splitlines())} lines, {tex.count('$') // 2 + tex.count(chr(92) + '[')} formulas")
    if "--build" in sys.argv:
        env = dict(os.environ, PATH=os.path.expanduser("~/.local/bin") + os.pathsep + os.environ["PATH"])
        r = subprocess.run(["latexmk", "-pdf", "-interaction=nonstopmode", "-halt-on-error", os.path.basename(DST)],
                           cwd=OUT_DIR, env=env, capture_output=True, text=True)
        log = open(DST[:-4] + ".log", errors="replace").read() if os.path.exists(DST[:-4] + ".log") else r.stdout
        if r.returncode:
            print("\n".join(l for l in log.splitlines() if l.startswith("!") or l.startswith("l."))[:3000])
            sys.exit(1)
        subprocess.run(["latexmk", "-c", os.path.basename(DST)], cwd=OUT_DIR, env=env, capture_output=True)
        pages = re.search(r"Output written on .*?\((\d+) pages", log)
        over = re.findall(r"^Overfull \\hbox \(([\d.]+)pt", log, re.M)
        print(f"{DST[:-4]}.pdf: {pages.group(1) if pages else '?'} pages, {len(over)} overfull lines"
              + (f" (largest {max(map(float, over)):.0f}pt)" if over else ""))


if __name__ == "__main__":
    main()
